import pytest

from tests.tests_resources.data_for_testing import PROCESSED_ROOT, TEST_PROJECT

pytestmark = pytest.mark.integration


def test_create_yaml():
    from flexiznam.camp.sync_data import create_yaml

    path2yaml = PROCESSED_ROOT / "mouse_physio_2p"
    create_yaml(
        path2yaml,
        TEST_PROJECT,
        origin_name="PZAA15.1a",
        output_file=path2yaml / "autogenerated_test.yaml",
        overwrite=True,
    )
