import pathlib
import yaml
from click.testing import CliRunner
from flexiznam import cli
from flexiznam.config import utils


def test_config(tmp_path):
    runner = CliRunner()
    result = runner.invoke(cli.config, ['--config_folder', tmp_path])
    assert result.exit_code == 0
    assert result.output.startswith('No configuration file. Creating one.')
    assert pathlib.Path.exists(tmp_path / 'config.yml')
    prm = utils.load_param(param_folder=tmp_path)
    assert prm['camp']['raw_data_source'] == r'D:\Data'
    result = runner.invoke(cli.config, ['--config_folder', tmp_path])
    assert result.exit_code == 0
    assert result.output.startswith('Configuration file currently used is:')
    str_cfg = yaml.dump(utils.DEFAULT_CONFIG) + '\n'
    assert result.output.endswith(str_cfg)


def test_add_password(tmp_path):
    runner = CliRunner()
    pwd_file = tmp_path / 'pass.yml'
    result = runner.invoke(cli.add_password, ['--password_file', pwd_file,
                                              '--app', 'test_app', '--username', 'noone',
                                              '--password', '1234'])
    assert result.exit_code == 0
    assert result.output.startswith('Password added in')
    p = utils.get_password(username='noone', app='test_app', password_file=pwd_file)
    assert p == '1234'


def test_make_full_yaml(tmp_path):
    znm_folder = pathlib.Path(__file__).parent.absolute()
    path_to_full_yaml = znm_folder / '..' / 'flexiznam' / 'camp' / 'example_acquisition_yaml.yml'
    path_to_mini_yaml = znm_folder / '..' / 'flexiznam' / 'camp' / 'minimal_example_acquisition_yaml.yml'
    runner = CliRunner()
    out_yml = tmp_path / 'autogenerated.yml'
    result = runner.invoke(cli.make_full_yaml, ['-s', path_to_mini_yaml, '-t', out_yml])
    assert result.exit_code == 0
    # read auto yaml
    with open(out_yml, 'r') as reader:
        auto_out = yaml.safe_load(reader)
    assert len(auto_out) == 10
    result = runner.invoke(cli.make_full_yaml, ['-s', path_to_full_yaml, '-t', out_yml])
    assert result.exit_code == 0
    # read auto yaml
    with open(out_yml, 'r') as reader:
        auto_out = yaml.safe_load(reader)
    assert len(auto_out) == 10
