# This is an example file.
# If you don't want to specify your credential at every function call
# place them in this file and rename it as "secret_password.yml"

flexilims:
  username: password
  username2: another_password
mcms:
  username: password
